@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M
participant "Apuntes" as A 
participant "Flashcards" as F 
participant "Respuesta" as R 




Estudiante -> UI: Selecciona "Crear flashcards"
UI -> M: Solicita lista de materias (id_usuario)
M -> M: exports.obtenerTodas(id_usuario)
M --> UI: Lista vacía
Alt No está la materia deseada / No existen materias registradas
    Estudiante -> UI: Selecciona Crear Materia
    Ref over Estudiante, UI, M: Ir a caso de uso: Crear Materia.
end 
@enduml







