@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M


' === FASE 1: Acceso a la sección de materias ===
Estudiante -> UI: Selecciona "Materias"
UI -> M: Solicita lista de materias (id_usuario)
M -> M: exports.obtenerTodas(id_usuario)
M --> UI: Lista de materias
UI --> Estudiante: Muestra sección de materias

' === FASE 2: Formulario de creación ===
Estudiante -> UI: Selecciona "Crear materia"

' === FASE 3: Creación fallida por campos incompletos ===
Estudiante -> UI: Ingresa dato(nombre, descripción)
UI -> M: Solicita crear materia (id_usuario, nombre_materia, descripcion)
M -> M: exports.crear(id_usuario, nombre_materia, descripcion)
alt Campos incompletos
    M --> UI: Error, campo(s) vacío(s)
    UI --> Estudiante: Muestra error de campos incompletos
end


@enduml





