@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M
participant "Apuntes" as A 
participant "Flashcards" as F 
participant "Respuesta" as R 




Estudiante -> UI: Selecciona "Crear flashcards"
UI -> M: Solicita lista de materias (id_usuario)
M -> M: exports.obtenerTodas(id_usuario)
M --> UI: Lista de materias
UI --> Estudiante: Muestra lista de materias
Estudiante -> UI: Selecciona materia existente


Alt Archivo inválido
Estudiante -> UI: Carga archivo (.pdf/.docx/.doc/.ppt)
Estudiante -> UI: Selecciona archivo 
UI --> Estudiante: Muestra error de archivo inválido
UI --> Estudiante: Muestra intefaz de selección de archivo
end
@enduml






