@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M
participant "Apuntes" as A 
participant "Flashcards" as F 
participant "Respuesta" as R 


UI --> Estudiante: Muestra menú
Estudiante -> UI: Selecciona "Crear flashcards"
UI --> Estudiante: Interfaz pregunta por la pertenencia del apunte
UI -> M: Solicita lista de materias(id_usuario)
M -> M : exports.obtenerTodas(id_usuario)
M --> UI: Lista de materias
Estudiante -> UI: Selecciona materia existente
UI --> Estudiante: Muestra intefaz de selección de archivo
Estudiante -> UI: Carga archivo (.pdf/.docx/.doc/.ppt)
UI --> Estudiante: Muestra interfaz de subir el archivo
Estudiante -> UI: Selecciona subir archivo
UI -> A: Solicita crear apunte (id_materia, titulo, ruta_archivo, tipo_archivo, tamaño_bytes)
A -> A: exports.crear(id_materia, titulo, ruta_archivo, tipo_archivo, tamaño_bytes)
A -> A: Guarda el archivo
A --> UI: Apunte válido
UI --> Estudiante: Muestra interfaz de generar flashcards con IA
UI -> F: exports.generarYGuardar(id_apunte)
F -> A: exports.obtenerPorId(id_apunte)
A --> F: Datos del apunte (título, ruta)
F ->: aiService.generarFlashcardsDesdeArchivo(ruta, tipo, titulo)

alt Error en el procesamiento del archivo
    F <--: Error
    F --> UI: Error: "No se pudo procesar el apunte"
    UI --> Estudiante: Muestra la notificación del error
    UI --> Estudiante: Muestra interfaz de Generar flashcards con IA
end