@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M
participant "Apuntes" as A 
participant "Flashcards" as F 
participant "Respuesta" as R 




' === FASE 1: Selección de materia ===
Estudiante -> UI: Selecciona "Crear flashcards"
UI -> M: Solicita lista de materias (id_usuario)
M -> M: exports.obtenerTodas(id_usuario)
M --> UI: Lista de materias
UI --> Estudiante: Muestra lista de materias

' === FASE 2: Carga de archivo ===
Estudiante -> UI: Selecciona materia existente
Estudiante -> UI: Carga archivo (.pdf/.docx/.doc/.ppt)
Estudiante -> UI: Confirma subir archivo
UI -> A: Solicita crear el apunte (id_materia, titulo, ruta_archivo, tipo_archivo, tamaño_bytes)
A -> A: exports.crear(id_materia, titulo, ruta_archivo, tipo_archivo, tamaño_bytes)
A --> UI: Apunte creado (id_apunte)

' === FASE 3: Generación IA de flashcards ===
UI --> Estudiante: Interfaz de Generar flashcards con IA
Estudiante -> UI: Selecciona Generar flashcards con IA
UI -> F: exports.generarYGuardar(id_apunte)
F -> A: Solicita datos del apunte (id_apunte)
A -> A: exports.obtenerPorId(id_apunte)
A --> F: Datos del apunte (titulo, ruta, tipo)
F ->: aiService.generarFlashcardsDesdeArchivo(ruta, tipo, titulo)

Alt Flashcards no son almacenadas (Error SQL)
    F <--: JSON con flashcards (título, pregunta, respuestas[])
    F -> F: Rollback
    R -> R: Rollback
    F --> UI: Informa error de base de datos
    UI --> Estudiante: Notifica error y solicita reintentar
end

@enduml



