@startuml
actor Estudiante
participant "Interfaz" as UI
participant "Materias" as M
participant "Apuntes" as A
participant "Flashcards" as F
participant "Respuesta" as R


UI --> Estudiante: Muestra menú
Estudiante -> UI: Selecciona "Usar flashcards"
UI --> Estudiante: Muestra sección de selección de materia
Estudiante -> UI: Selección de materia
UI --> Estudiante: Muestra interfaz de opciones de uso de flashcards
Estudiante -> UI: Selecciona ver todas las respuestas
UI -> F: solicita las flashcards con respuestas (id_materia)
F -> F: exports.obtenerPorMateriaConRespuestas(id_materia)
F -> R: cargarRespuestasParaFlashcards(id_materia)
F --> UI: Lista de preguntas
R --> UI: Lista de respuestas
UI --> Estudiante: Interfaz muestra vista de tarjeta de pregunta con respuesta